# -*- coding: utf-8 -*-
"""Viva_config.ipynb

#Automatically generated by Colab.

# -*- coding: utf-8 -*-

================================================================================
 FACULTY CONFIGURATION FILE — edit ONLY this file to set up the Viva Agent
 for your own subject. You do not need to open or understand viva_gen.py.
================================================================================

HOW TO REUSE THIS APP FOR A DIFFERENT SUBJECT / A DIFFERENT FACULTY MEMBER
--------------------------------------------------------------------------
1. Copy the whole project folder (viva_gen.py + this file + requirements.txt
   + any secrets setup) into a new folder — e.g. "viva_finance/",
   "viva_marketing/", "viva_hr/".
2. In the COPY, edit the values below to match that faculty's subject,
   difficulty level, question count and time limit.
3. Deploy the copy as its own Streamlit app (its own URL / its own Streamlit
   Cloud deployment). Each faculty member ends up with an independently
   configured viva agent, without ever touching the underlying app code.
4. Nothing else needs to change — viva_gen.py automatically reads the
   values below when it starts.

This keeps the "engine" (viva_gen.py) identical and untouched across every
faculty deployment, while every subject-specific choice lives in one short,
readable file that a non-programmer can safely edit.
================================================================================
"""

# The subject this viva is locked to. Shown to students as read-only in the
# sidebar. Set to "" (empty string) instead if you want faculty/TAs running
# the app to pick the subject themselves from a dropdown each session.
VIVA_SUBJECT = "Organizational Behaviour"

# Difficulty of questioning. One of: "Easy", "Standard", "Rigorous"
# Set to "" (empty string) to let the person running the app choose it
# from a dropdown instead of locking it.
VIVA_DIFFICULTY = "Standard"

# How many student/examiner exchanges happen before the viva auto-completes.
VIVA_TOTAL_QUESTIONS = 10

# Hard time limit for the whole viva, in minutes. Set to 0 to disable the
# timer entirely (the viva will then only end based on VIVA_TOTAL_QUESTIONS).
VIVA_TIME_LIMIT_MINUTES = 10

# Optional extra guidance for the examiner AI — use this to steer WHAT kind
# of questions get asked, without ever touching viva_gen.py. Leave as ""
# for the default question style. Examples of things you can put here:
#   - "Only ask questions about Chapters 3 and 4 (Methodology and Findings)."
#   - "Do not ask any numerical/calculation questions."
#   - "Every student must be asked to justify their sample size."
#   - "Focus questions on ethical implications of the recommendations."
# Keep it short and specific — a few bullet points work best. This text is
# added on top of, not instead of, the built-in one-question-at-a-time and
# scoring rules.
VIVA_CUSTOM_INSTRUCTIONS = """
-"ask questions on what they have mentioned in their report"
"""

# Optional list of SPECIFIC, exact-wording questions for this subject that
# every student must be asked at some point during their viva — use this
# when you have a fixed set of questions you want covered (a theory
# question bank, standard concept checks, etc.), as opposed to
# VIVA_CUSTOM_INSTRUCTIONS above which is general steering/guidance rather
# than exact question text. Leave as [] (empty list) if you don't need
# this. The examiner will weave these in one at a time alongside its own
# project-specific questions, not all back-to-back, and may phrase them
# slightly more naturally while keeping their meaning — they still count
# toward VIVA_TOTAL_QUESTIONS above, so don't list more than roughly half
# your total question count or there won't be room left for project-
# specific questions.


# Optional list shown in the Subject dropdown when VIVA_SUBJECT is "" above.
# Add/remove subjects here as your faculty roster changes.
AVAILABLE_SUBJECTS = [
    "Marketing Management",
    "Financial Management",
    "Human Resource Management",
    "Organizational Behaviour",
    "Organizational Behaviour 2",
    "Business Strategy",
]
